### ISSUE TITLE
Filename billing?

### ISSUE THREAD

**Issue by marcorosa** [Storj/billing#100]
Should file names be included in billing?
Once a contract expires, shards are deleted but file names don't, and remain visible inside the bucket.

An attacker could upload files with really long names and small size, so that when contracts expire he is still able to read data for free.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision here. This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [RocketChat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
