### ISSUE TITLE
Unable to remove credit card

### ISSUE THREAD

**Issue by SimplyCorey** [Storj/billing#64]
When I click on `remove card` the screen flashes, and the button says "Submitting."  After about 5 seconds, the card returns and the button says "Remove Card"

Here is the JSON response from the server:

```
{  
   "data":{  
      "paymentProcessor":{  
         "id":"XXXXX",
         "name":"STRIPE",
         "billingDate":7,
         "defaultPaymentMethod":{  
            "merchant":"Discover",
            "lastFour":"XXXX",
            "id":"card_1XXXXXX"
         },
         "error":null
      }
   }
}
```

**Comment by SimplyCorey** [comment]
My card was also charged two authorizations when I added the card if that helps re-create this issue.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision here. This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [RocketChat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
