### ISSUE TITLE
Being charged daily without having any buckets in my account

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#67]
![clipboard - august 5 2017 9-47 am 1](https://user-images.githubusercontent.com/11735738/28994341-7f60a040-79c3-11e7-9f14-267906bd349f.png)
![clipboard - august 5 2017 9-47 am](https://user-images.githubusercontent.com/11735738/28994342-7f642652-79c3-11e7-8d93-fedccc0dae7b.png)

I am being charged for used space every day yet i have no buckets in my account, why is that?

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision here. This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [RocketChat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
