### ISSUE TITLE
I want less mirrors for my files and i want to pay less

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/billing#68]
Currently i am paying 15$/TB for 6 mirrors per shard, i want 3 mirrors and i want to pay 7.5$/TB of used space.

**Comment by MeijeSibbel** [comment]
related to https://github.com/Storj/bridge/issues/476

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision here. This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [RocketChat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
