### ISSUE TITLE
I have usage of this month 76291344.13 GB, but only 419.00 GBh - what's going on?

### ISSUE THREAD

**Issue by AlexeyALeonov** [Storj/billing#81]
I'm get credit $10 to my Bridge account by clicking on the referral link.
![-10](https://user-images.githubusercontent.com/26858949/29998332-33a88a94-9031-11e7-9ba3-ad5ed6e98a0b.PNG)

And have a weird "usage" on the Billing page:
![image](https://user-images.githubusercontent.com/26858949/29998359-81a32114-9031-11e7-956d-74ccd2a8c577.png)

However my usage history never close to it:
![image](https://user-images.githubusercontent.com/26858949/29998334-3d518528-9031-11e7-8294-c94ba2e48d08.png)

**Comment by pgerbes1** [comment]
I did some research and found two issues causing the usage display to be off.

1) There are old debits in the database that have the number of bytes for storage instead of gbHours, though the amount billable is correct. That is why we are seeing really high numbers for some users. I have a migration script that will fix this. 

2) The front end (bridge-gui-vue) does not limit data to the current billing cycle and instead sums up total usage for all time. This explains how the malformed debits from issue number one are affecting usage statistics in the present. I am working on a PR to fix this as well.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision here. This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [RocketChat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
